[package]
name = "git-gud"
version = "0.1.0-alpha.3"
edition = "2024"
rust-version = "1.91.1"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.53", features = ["derive"] }
env_logger = "0.11.8"
log = "0.4.29"

[dev-dependencies]
itertools = "0.14.0"
